In [ ]:
#Verly Rahma Aulia
#NIM 2311501601

import numpy as np

A = np.array([[2, 3],
              [1, 1]])

B = np.array([[5, 0],
              [1, 6]])

C = np.array([0, 1])

# 1. A+B
D = A + B
print("1. A + B =\n", D)

# 2. B-A
E = B - A
print("2. B - A =\n", E)

# 3. 5A
F = 5 * A
print("3. 5A =\n", F)

# 4. det(A)
G = np.linalg.det(A)
print("4. det(A) =\n", G)

# 5. B Inverse
H = np.linalg.inv(B)
print("5. B Inverse =\n", H)

# 6. A x C
I = np.dot(A, C)
print("6. A x C =\n", I)

# 7. C transpose x A 
J = np.dot(C.T, A)
print("7. C transpose x A =\n", J)

# 8. A x B transpose
K = np.dot(A, B.T)
print("8. A x B transpose =\n", K)

# 9. A transpose + B x C
L = A.T + np.dot(B, C)
print("9. A transpose + B x C =\n", L)

# 10. A x B x C
M = np.dot(A, np.dot(B, C))
print("10. A x B x C =\n", M)

1. A + B =
 [[7 3]
 [2 7]]
2. B - A =
 [[ 3 -3]
 [ 0  5]]
3. 5A =
 [[10 15]
 [ 5  5]]
4. det(A) =
 -1.0
5. B Inverse =
 [[ 0.2         0.        ]
 [-0.03333333  0.16666667]]
6. A x C =
 [3 1]
7. C transpose x A =
 [1 1]
8. A x B transpose =
 [[10 20]
 [ 5  7]]
9. A transpose + B x C =
 [[2 7]
 [3 7]]
10. A x B x C =
 [18  6]
